iteration on radical-stack

diff --git a/bin/radical-stack-clone b/bin/radical-stack-clone
--- a/bin/radical-stack-clone
+++ b/bin/radical-stack-clone
@@ -6,92 +6,227 @@
 
 # ------------------------------------------------------------------------------
 #
-tmp="/tmp/radical-stack-tmp.$(id -u)"
-stack=$1
-ve_target=$2
+# default settings
+#
 cwd=`pwd`
+tmp="/tmp/radical-stack-tmp.$(id -u)"
 log="$stack.log"
+
+branch="devel"
+tag=
+stack=
+veloc=
+
 
 # ------------------------------------------------------------------------------
 #
 usage() {
+
     msg=$1
-    echo "\n\t$msg\n\tusage: $0 <stack> <ve_target>\n\n"
+
+    if ! test -z "$msg"
+    then
+        printf "\n    error: $msg\n" 
+    fi
+
+    cat <<EOT
+    
+    usage: $0 -v ve_location 
+             [-s stackfile] 
+             [-b branch]
+             [-t tag]
+
+    This utility will create a new (or update an existing) Python virtualenv
+    with a specific (set of) version(s) of the radical stack, including
+    radical.{pilot,saga,utils,analytics}.  The version to be used can be
+    specified in two ways: as a stackfile or as command line parameters.
+
+      -s stackfile: stackfile to use
+                    The file must be formatted as is the output of the 
+                    'radical-stack' command.
+
+      -b branch   : branch to install
+                    the branch should be exist for all layers -- otherwise
+                    'devel' is being used.
+
+      -b tag      : tag to install
+                    the tag should be exist for all layers -- otherwise the
+                    'devel' branch is being used.
+
+    example:
+
+--------------------------------------------------------------------------------
+$ ./bin/radical-stack-clone -v ve_test -t titan
+
+tag @ branch requested: titan@devel
+ve location  requested: ve_test
+
+check  virtualenv ve_test
+source virtualenv ve_test
+
+mod               repo                                                    branch  commit tag
+radical.utils     git@github.com:radical-cybertools/radical.utils.git     devel          titan
+saga-python       git@github.com:radical-cybertools/saga-python.git       devel          titan
+radical.pilot     git@github.com:radical-cybertools/radical.pilot.git     devel          titan
+radical.analytics git@github.com:radical-cybertools/radical.analytics.git devel          titan
+
+installed:
+python            : 2.7.12+
+virtualenv        : /home/merzky/radical/radical.utils/ve_test
+radical.utils     : titan@HEAD-detached-at-titan
+saga-python       : titan@HEAD-detached-at-titan
+radical.pilot     : titan@HEAD-detached-at-titan
+radical.analytics : v0.1-113-gb032808@devel
+--------------------------------------------------------------------------------
+
+EOT
+
     exit
 }
+
+
+# ------------------------------------------------------------------------------
+#
+# command line args can overwrite defaults
+#
+
+while getopts b:t:s:v: opt
+do
+    case $opt in
+    v)   veloc="$OPTARG";;
+    s)   stack="$OPTARG";;
+    b)   branch="$OPTARG";;
+    t)   tag="$OPTARG";;
+    ?)   usage "cannot handle argument $opt"
+         exit 2;;
+    esac
+done
+
+
+# ------------------------------------------------------------------------------
+#
+# some args are mandatory
+#
+if test -z "$veloc"
+then
+    usage "no virtualenv location specified"
+fi
+
+if test -z "$stack$branch$tag"
+then
+    usage 'missing stack file or branch'
+fi
+
+
+# ------------------------------------------------------------------------------
+#
+# report target stack
+#
+echo
+if ! test -z "$stack"
+then
+    printf "stack config requested: $stack\n$(echo $stack | grep ':')"
+else
+    printf "tag @ branch requested: $tag@$branch\n"
+fi
+
+printf "ve location  requested: $veloc\n\n"
+
 
 # ------------------------------------------------------------------------------
 #
 install() {
 
     mod="$1"
-    info="$2"
+    repo="$2"
+    branch="$3"
+    tag="$4"
+    commit="$5"
 
-    repo="git@github.com:radical-cybertools/$mod.git"
-
-    spec=$(  echo "$info" | cut -f 2 -d ':' | xargs echo)
-    branch=$(echo "$spec" | cut -f 2 -d '@' | tr '-' '/')
-    commit=$(echo "$spec" | sed -e 's/.*-g\([a-zA-Z0-9]*\)@.*/\1/g')
-    tag=$(   echo "$spec" | cut -f 1 -d '-')
-
-    printf "%-20s  %-55s  %-30s %-30s %s\n" "$mod" "$repo" "$branch" "$commit" "$tag"
+    printf "%-20s  %-55s  %-30s %-30s %s\n" "$mod" "$repo" "$branch" "$commit" "$tag" \
+        | tee -a $log
 
     if ! test -d "$tmp/$repo"
     then
-        git clone $repo $tmp/$repo 2>&1 >> $log
+        git clone "$repo" "$tmp/$repo" 2>&1 >> $log
     fi
 
+  # set -x
+
     cd $tmp/$repo
-    git pull --all        >> $log 2>&1
-    git checkout $branch  >> $log 2>&1
-    git checkout $commit  >> $log 2>&1
-    pip uninstall -y $mod >> $log 2>&1
-    pip install .         >> $log 2>&1
+    git pull --all                              >> $log 2>&1
+    test -z "$branch" || git checkout "$branch" >> $log 2>&1
+    test -z "$tag"    || git checkout "$tag"    >> $log 2>&1
+    test -z "$commit" || git checkout "$commit" >> $log 2>&1
+    pip uninstall -y $mod                       >> $log 2>&1
+    pip install .                               >> $log 2>&1
     cd $cwd
+
+  # set +x
 }
 
 
 # ------------------------------------------------------------------------------
 #
-if test -z "$stack"
+# create / activate ve
+#
+if ! test -d "$veloc"
 then
-    usage 'missing input stack'
+    printf "create virtualenv $veloc\n"
+    virtualenv    "$veloc" >> $log 2>&1
+else
+    printf "check  virtualenv $veloc\n"
+    test -d $veloc || echo "ve invalid!" || exit 1
 fi
 
-if test -z "$ve_target"
-then
-    usage 'missing target ve'
-fi
+printf "source virtualenv $veloc\n\n"
+. "$veloc/bin/activate"
 
-if ! test -d "$ve_target"
-then
-    echo "create   $ve_target"
-    virtualenv    "$ve_target" >> $log 2>&1
-fi
 
-. "$ve_target/bin/activate"
-
+# output header
 printf "%-20s  %-55s  %-30s %-30s %s\n" "mod" "repo" "branch" "commit" "tag"
 
-for mod in 'radical.utils' 'saga-python' 'radical.pilot' 'radical.analytics'
-do
-    ru_info=$(cat $stack | grep -e "^$mod" | tail -n 1)
-    if test -z "$ru_info"
-    then
-        echo "skip $mod"
-    else
-        install "$mod" "$ru_info"
-    fi
-done
+
+# ------------------------------------------------------------------------------
+#
+# install from stack file
+#
+if ! test -z "$stack"
+then
+    for mod in 'radical.utils' 'saga-python' 'radical.pilot' 'radical.analytics'
+    do
+        info=$(cat $stack | grep -e "^$mod" | tail -n 1)
+        if test -z "$info"
+        then
+            echo "skip $mod"
+        else
+            repo="git@github.com:radical-cybertools/$mod.git"
+
+            spec=$(  echo "$info" | cut -f 2 -d ':' | xargs echo)
+            branch=$(echo "$spec" | cut -f 2 -d '@' | tr '-' '/')
+            commit=$(echo "$spec" | sed -e 's/.*-g\([a-zA-Z0-9]*\)@.*/\1/g')
+            tag=$(   echo "$spec" | cut -f 1 -d '-')
+
+            install "$mod" "$repo" "$branch" "$tag" "$commit"
+        fi
+    done
+
+else
+    for mod in 'radical.utils' 'saga-python' 'radical.pilot' 'radical.analytics'
+    do
+        repo="git@github.com:radical-cybertools/$mod.git"
+
+        install "$mod" "$repo" "$branch" "$tag" "$commit"
+        
+    done
+fi
 
 cd $cwd
 
 # verify
-echo '---------------'
-cat $stack | grep ':'
-echo '---------------'
-$ve_target/bin/python `which radical-stack`
-echo '---------------'
+printf "\ninstalled:\n"
+$veloc/bin/python `which radical-stack`
+echo
 
 # ------------------------------------------------------------------------------
 
